language: python
python:
  - '3.5'
branches:
  only:
    - 'demo'
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py test
  - coverage run --source=djangocupcakeshop,menu manage.py test
notifications:
  email: false
after_success:
  coveralls
